spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///maven?useUnicode=true&characterEncoding=utf8&useSSL=false&&serverTimezone=UTC
    username: root
    password: 0438424142c
  application:
    name: items-service

mybatis:
  type-aliases-package: com.demo.cg.pojo

server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka

logging:
  level:
    com.demo.cg: debug